### ISSUE TITLE
Add WebP support

### ISSUE THREAD

**Issue by LBlend** [TechnikTobi/little_exif#1]
This may be a shot in the dark is the project hasn't gotten any commits in a while but I really like the interface that this library provides and would highly appreciate WebP support

**Comment by TechnikTobi** [comment]
Will do.

**Comment by TechnikTobi** [comment]
I've added some basic WebP support. This should now work with extended .webp files - see https://developers.google.com/speed/webp/docs/riff_container#extended_file_format what this means. Basically, the file needs to have a VP8X chunk (the simple versions don't have one of those and thus don't support EXIF data). There is the plan to add a converter so that files get a VP8X if they don't have one, but I wanted to get a first version out asap for you to test & give feedback.

**Comment by LBlend** [comment]
> I've added some basic WebP support. This should now work with extended .webp files - see https://developers.google.com/speed/webp/docs/riff_container#extended_file_format what this means. Basically, the file needs to have a VP8X chunk (the simple versions don't have one of those and thus don't support EXIF data). There is the plan to add a converter so that files get a VP8X if they don't have one, but I wanted to get a first version out asap for you to test & give feedback.

Great! I will check it out and play around with it when I get the time to! I'll post an update about it then. Thank you!

**Comment by TechnikTobi** [comment]
Closing this issue. 
- Reason: No feedback received.
- Note: Converter for VP8X chunk added to ToDo list; postponed for now.
