### ISSUE TITLE
works nicely, but still messages

### ISSUE THREAD

**Issue by mschnell1** [TechnikTobi/little_exif#28]
Within the 1500 jpg files under test several show library messages: 

- Could not validate EXIF header!

- Error during decoding: Custom { kind: Other, error: "No EXIF data found!" }

- Could not get IFD0 tags:
 Could not decode SubIFD:
 Illegal format for known tag! Tag: FocalLengthIn35mmFormat([]) Expected: INT16U Got: INT32U

- Error during decoding: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }

Do you want example files ?

**Comment by TechnikTobi** [comment]
Hi,

short update from my side:
- I'm currently working on a new encoder and decoder in order to support TIFF data, as well as resolve some of the previously opened issues. This is required to properly handle the different image file directories that construct the EXIF and TIFF data - so far some shortcuts were taken here that worked for the majority of files, but not for others.
- Apart from that I'm currently fighting a cold for the last couple of days and I am thus unable to work for extended amounts of time on the new de- and encoder. 

Because of these two reasons, work has been slowed down significantly and will likely take at least another week before any significant update can be released. 

Regarding the new issues: Yes, example files are *always* welcomed to better understand what is going on :) 

Best,
Tobi

**Comment by mschnell1** [comment]
Here example files: 

Error during decoding: Custom { kind: Other, error: "No EXIF data found!" }
www.bitvibe.de/Upload/2017_stockholm_emilio.jpg

Could not get IFD0 tags:
 Could not decode SubIFD:
  Illegal format for known tag! Tag: FocalLengthIn35mmFormat([]) Expected: INT16U Got: INT32U
www.bitvibe.de/Upload/aachen_abendhimmel_emilio.jpg

Error during decoding: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }
www.bitvibe.de/Upload/isernhagen_sorento_1.jpg
