### ISSUE TITLE
TumbsPlus does not read or write exif data with some files written by Little Exif

### ISSUE THREAD

**Issue by mschnell1** [TechnikTobi/little_exif#29]
When I have Little Exif work on a JPG file and it for some reason does not decently detect EXIF data (either because there are none or due to issues described in #28 ) ThumbsPlus does not show any Exif for that file, eve if I pushed `ImageDescription` onto  in. (I tested also pushing `Artist` but no change).
Windows Explorer "Details" does correctly show the `ImageDescription` string as "Titel" (and funnily also as "Betreff" - which might be a hint...) (More fun: ThumbsPlus seemingly denotes "Title" to something else and uses "Comments" for Image "Description".
ThumbsPlus does not provide any error message when reading the file. 
But when I try to set an Exif Value (e.g. "Artist" <aka "Creator" in ThumbsPlus>), I do get an error message: 
```
unable to update XMP: 
error #000000ce,
bad IFD offset. 
```
Of course I can't know if the problem is with ThumbsPlus or with Little Exif. Some kind of incompatibility. :(

**Comment by TechnikTobi** [comment]
Still working on the encoder, so I can't tell yet. However, I have a question: What about images that are processed fine by little_exif? I presume that the Windows Explorer shows everything as you'd expect, but what about ThumbsPlus? Does it show the edited metadata or still the old one? I'm asking this because of the error message regarding XMP metadata, which is something different but still related. If ThumbsPlus relies only on XMP then you should see the unedited data - this would also explain why no ImageDescription gets displayed (as TP would look in the wrong place in this case).

**Comment by mschnell1** [comment]
As far as I tested, filed that do have a bunch of metadata and those are seen in ThumbsPlus and that can be decoded by LittleExif, and I then set `ImageDescription` to a new string, write the metadata back and then write a new file, those files are processed by ThumbsPlus without a problem and the new `ImageDescription` is shown and imported in the Database as "Annotation". Both if `ImageDescription` was not set before and if it was overwritten by Little Exif.

**Comment by mschnell1** [comment]
I don't know if this still is relevant.
I seem to have found that the files ThumbsPlus does not decode, also result in Errors,when trying to decode Them with Little_Exif.

**Comment by TechnikTobi** [comment]
Does this problem still persist with the 0.6.0 beta?

**Comment by TechnikTobi** [comment]
I assume we can close this issue?
