### ISSUE TITLE
Panic on certain Files

### ISSUE THREAD

**Issue by User65k** [TechnikTobi/little_exif#51]
I am running into a panic with a bunch of different files.
Dolphin (KDE) shows the EXIF information, as does Nextcloud.

I think it should return some Error (`IOError::other?`) or even better: just work :smile_cat: 

```
thread 'main' panicked at /home/User64k/.cargo/registry/src/index.crates.io-6f17d22bba15001f/little_exif-0.6.1/src/ifd/mod.rs:311:68:
called `Result::unwrap()` on an `Err` value: "Not a INT16U compatible tag!"
```

https://github.com/TechnikTobi/little_exif/blob/5c3a266c690fa9c412a81842d39449647ada7205/src/ifd/mod.rs#L311

I can provide one of the files if needed

**Comment by TechnikTobi** [comment]
Hi! Yes, please provide an example file as this is usually caused by images with tags that don't conform to the EXIF specifications and need special treatment. 

Unfortunately, finding out which tags these are requires a trial-and-error approach (as "not conforming to the specifications" is, by definition, knowledge that is not available in any specification :/ )

**Comment by TechnikTobi** [comment]
Update: You may want to try this again with v0.6.2 - please let me know if this issue still persists.

**Comment by User65k** [comment]
yes, 0.6.2 reads the EXIF information.
Thank you!
